env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
  extraFileExtensions:
    - ".svelte"
plugins:
  - "@typescript-eslint"
overrides:
  - files:
      - "*.svelte"
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": "off"
