name = "fileplay"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2023-05-18"

[build]
command = "npm run build"

[env.preview]
[[d1_databases]]
binding = "DB"
database_name = "fileplay-dev"
database_id = "49d8462f-a969-475f-82b6-5f70ecd13421"

[env.production]
[[d1_databases]]
binding = "DB"
database_name = "fileplay-prod"
database_id = "4ce6378e-473b-4a2e-8401-7f3407ed6784"
