name = "fileplay"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2023-05-18"

[build]
command = "npm run build"

[env.preview]

[[d1_databases]]
binding = "DB"
database_name = "fileplay-dev"
database_id = "14603b6b-a017-44fb-a201-d00ba618aba1"

[env.production]

[[d1_databases]]
binding = "DB"
database_name = "fileplay-prod"
database_id = "efd8d0f3-cb40-4a8c-b74b-207d0b7398cc"
