DROP TABLE IF EXISTS devices_link_codes CASCADE;

DROP TABLE IF EXISTS contacts_link_codes CASCADE;

DROP INDEX IF EXISTS idx_contacts_a;

DROP INDEX IF EXISTS idx_contacts_b;

DROP TABLE IF EXISTS contacts CASCADE;

DROP TABLE IF EXISTS groups CASCADE;

DROP TABLE IF EXISTS group_members CASCADE;

DROP TABLE IF EXISTS group_requests CASCADE;

DROP INDEX IF EXISTS idx_devices_uid;

DROP TABLE IF EXISTS devices CASCADE;

DROP TABLE IF EXISTS users CASCADE;