CREATE TABLE IF NOT EXISTS User (
	id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  lastSeen INTEGER DEFAULT CURRENT_TIMESTAMP,
	avatarSeed TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Device (
  id TEXT PRIMARY KEY,
  userId INTEGER NOT NULL,
  authHash TEXT NOT NULL,
  isOnline INTEGER DEFAULT 0,
  lastSeen INTEGER DEFAULT CURRENT_TIMESTAMP,
  webPushEndpoint TEXT,
  webPushP256DH TEXT,
  webPushAuth TEXT,  
  FOREIGN KEY(userId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS UserToDevice (
  userId TEXT NOT NULL,
  deviceId TEXT NOT NULL,
  FOREIGN KEY(userId) REFERENCES User(id),
  FOREIGN KEY(deviceId) REFERENCES Device(id),
  PRIMARY KEY(userId, deviceId)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS Contacts (
  fromId TEXT NOT NULL,
  toId TEXT NOT NULL,
  FOREIGN KEY(fromId) REFERENCES User(id),
  FOREIGN KEY(toId) REFERENCES User(id),
  PRIMARY KEY(fromId, toId)
)
