type User {
  id: ID!
  displayName: String!
  isOnline: Boolean!
  lastSeen: DateTime!
  avatarSeed: String!
  contactList: UserContactList!
  deviceList: UserDeviceList!
}

type UserContactList {
  contacts: [User!]!
}

type UserDeviceList {
  devices: [Device!]!
}

type Device
  @auth(
    query: {
      rule: "query ($ID: [ID!]) {queryDevice(filter: {id: $ID}) {__typename} }"
    }
  ) {
  id: ID!
  displayName: String!
  isOnline: Boolean!
  lastSeen: DateTime!
  owner: User!
}
