name: GraphQL Schema

on:
  push:
    branches:
      - main
      - dev

jobs:
  update-schema-prod:
    name: Update (Prod)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      DOTENV_KEY: ${{ secrets.DOTENV_KEY_PROD }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update Dgraph GraphQL schema
        run: |
          node .github/workflows/update-schema.js

  update-schema-dev:
    name: Update (Dev)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    env:
      DOTENV_KEY: ${{ secrets.DOTENV_KEY_DEV }} # todox add keys in github
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update Dgraph GraphQL schema
        run: |
          node .github/workflows/update-schema.js

  validate-schema:
    name: Validate
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'
    env:
      DOTENV_KEY: ${{ secrets.DOTENV_KEY_DEV }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Validate Dgraph GraphQL schema
        run: |
          node .github/workflows/validate-schema.js

      
